aex05: enoStrLightmapper.cpp enoLightmapper.cpp enoColormapper.cpp arduinoEx05.ino
	g++ -o aex05 enoStrLightmapper.cpp enoLightmapper.cpp enoColormapper.cpp asc/SerialCommands.cpp asc/kbhit.c asc/getch.c arduinoEx05.ino -I asc

ecslTest04: enoStrLightmapper.cpp enoLightmapper.cpp enoColormapper.cpp ecslTest04.cpp 
	g++ -o ecslTest04 enoStrLightmapper.cpp enoLightmapper.cpp enoColormapper.cpp asc/SerialCommands.cpp asc/kbhit.c asc/getch.c ecslTest04.cpp -I asc

ecslTest03: enoStrLightmapper.cpp enoLightmapper.cpp enoColormapper.cpp ecslTest03.cpp 
	g++ -o ecslTest03 enoStrLightmapper.cpp enoLightmapper.cpp enoColormapper.cpp asc/SerialCommands.cpp asc/kbhit.c asc/getch.c ecslTest03.cpp -I asc

ecslTest01: enoStrLightmapper.cpp enoLightmapper.cpp enoColormapper.cpp ecslTest01.cpp
	g++ -o ecslTest01 enoStrLightmapper.cpp enoLightmapper.cpp enoColormapper.cpp ecslTest01.cpp

