ecslTest03: enoStrLightmapper.cpp enoLightmapper.cpp enoColormapper.cpp ecslTest03.cpp 
	g++ -o ecslTest03 enoStrLightmapper.cpp enoLightmapper.cpp enoColormapper.cpp asc/SerialCommands.cpp asc/kbhit.c asc/getch.c ecslTest03.cpp -I asc

ecslTest01: enoStrLightmapper.cpp enoLightmapper.cpp enoColormapper.cpp ecslTest01.cpp
	g++ -o ecslTest01 enoStrLightmapper.cpp enoLightmapper.cpp enoColormapper.cpp ecslTest01.cpp

